DELETE FROM STORE_INFORMATION;
DELETE FROM GEOGRAPHY;

INSERT INTO GEOGRAPHY (GEOGRAPHY_ID,REGION_NAME) values (1,'East');
INSERT INTO GEOGRAPHY (GEOGRAPHY_ID,REGION_NAME) values (2,'West');
INSERT INTO GEOGRAPHY (GEOGRAPHY_ID,REGION_NAME) values (3,'North');

INSERT INTO STORE_INFORMATION (STORE_ID,STORE_NAME,SALES,STORE_DATE,GEOGRAPHY_ID) VALUES (1,'Boston',700,STR_TO_DATE('2018-03-09 00:00:00',"%Y-%m-%d %H:%i:%s") , 1);
INSERT INTO STORE_INFORMATION (STORE_ID,STORE_NAME,SALES,STORE_DATE,GEOGRAPHY_ID) VALUES (2,'Los Angeles',1500,STR_TO_DATE("2018-04-05 00:00:00","%Y-%m-%d %H:%i:%s"),2);
INSERT INTO STORE_INFORMATION (STORE_ID,STORE_NAME,SALES,STORE_DATE,GEOGRAPHY_ID) VALUES (3,'San Diego',250,STR_TO_DATE('2018-01-07 00:00:00',"%Y-%m-%d %H:%i:%s"),2);
INSERT INTO STORE_INFORMATION (STORE_ID,STORE_NAME,SALES,STORE_DATE,GEOGRAPHY_ID) VALUES (4,'Los Angeles',300,STR_TO_DATE('2018-02-07 00:00:00',"%Y-%m-%d %H:%i:%s"),2);
INSERT INTO STORE_INFORMATION (STORE_ID,STORE_NAME,SALES,STORE_DATE,GEOGRAPHY_ID) VALUES (5,'Albany, Crossgates',2500,STR_TO_DATE('2018-05-15 00:00:00',"%Y-%m-%d %H:%i:%s"),2);
INSERT INTO STORE_INFORMATION (STORE_ID,STORE_NAME,SALES,STORE_DATE,GEOGRAPHY_ID) VALUES (6,'Buffalo, Walden Galleria',3000,STR_TO_DATE('2018-06-10 00:00:00',"%Y-%m-%d %H:%i:%s"),NULL);
                                       